name: Playwright CI

on:
  push:
    branches:
      - main

env:
  DOTNET_VERSION: '8.0.x'
  TARGET_FRAMEWORK: 'net8.0'
  BUILD_CONFIGURATION: 'Release'
  PROJECT_PATH: 'PlaywrightPipelineDemo.csproj'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}

      - name: Restore NuGet packages
        run: dotnet restore ${{ env.PROJECT_PATH }}

      - name: Build Playwright project
        run: dotnet build ${{ env.PROJECT_PATH }} --configuration ${{ env.BUILD_CONFIGURATION }} --no-restore

      - name: Upload build output
        uses: actions/upload-artifact@v4
        with:
         name: playwright-build
         path: bin/${{ env.BUILD_CONFIGURATION }}/${{ env.TARGET_FRAMEWORK }}
         include-hidden-files: true

  test:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}

      - name: Download build output
        uses: actions/download-artifact@v4
        with:
          name: playwright-build
          path: bin/${{ env.BUILD_CONFIGURATION }}/${{ env.TARGET_FRAMEWORK }}

      - name: Install Playwright browsers and dependencies
        run: pwsh bin/${{ env.BUILD_CONFIGURATION }}/${{ env.TARGET_FRAMEWORK }}/playwright.ps1 install --with-deps

      - name: Run Playwright tests
        env:
          BASE_URL: ${{ secrets.BASE_URL }}
        run: dotnet test ${{ env.PROJECT_PATH }} --configuration ${{ env.BUILD_CONFIGURATION }} --no-build